### ISSUE TITLE
The script fails to run repeatedly.

### ISSUE THREAD

**Issue by vis-ikeda** [gw-vis/pcas-controller#3]
何度か試しているとscripts側が死ぬことがあり要調査

Traceback (most recent call last):
File "/kagra/apps/pcaspy/lib/python2.7/site-packages/pcaspy/driver.py", line 450, in getValue
newValue = driver.read(self.info.reason)
File "steppingmotor/pcasip.py", line 210, in read
value = self.driver.getLeftLimitSwitch(motorAddrC)
File "steppingmotor/Trinamic_control6110.py", line 528, in getLeftLimitSwitch
data = self.receiveData()
File "steppingmotor/Trinamic_control6110.py", line 94, in receiveData
RxBuffer = self.port.recv(9)
socket.timeout: timed out
Traceback (most recent call last):
File "/kagra/apps/pcaspy/lib/python2.7/site-packages/pcaspy/cas.py", line 416, in read
def read(self, *args): return _cas.PV_read(self, *args)
RuntimeError: SWIG director method error. Exception Calling Python Code
filename="../../../../src/cas/generic/st/casStreamOS.cc" line number=479
Internal failure - unexpected problem with client's input - forcing disconnect
/kagra/apps/pcaspy/lib/python2.7/site-packages/pcaspy/cas.py:235: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
if primitiveType in [aitEnumUint8, aitEnumInt8]:

**Comment by vis-ikeda** [comment]
>         if (name == "UPDATE") and (value == 1.0):
>             self.driver.reconnect()

reconnect()を削除したら発生しなくなった。
reconnect()を呼ばなくても正常に動作する。
接続状態なのに呼ぶタイミングはおかしい。
なぜ入っているか不明！？
とりあえず削除して進めて異常が発生したら別の手段で修正予定。

**Comment by terrencetec** [comment]
Can we simply use something like:
```
while 1:
    try:
        ...
        break
    except RuntimeError as e:
        logger.error(str(e))
        pass
```
to bypass the error?

**Comment by vis-ikeda** [comment]
Thanks for the advice.

This case is an idea that needs to be addressed more fundamentally than error avoidance with try-except.
I think error avoidance should be put in for irregular errors first, after it works correctly.
Maybe calling reconnect() is the wrong thing to do.
If reconnect() is necessary, we think it needs to be called conditionally.

**Comment by vis-ikeda** [comment]
直前のコマンド送出後に結果を受信するが
k1scriptの処理負荷による遅延によって処理が回ってこない場合に
タイムアウトが発生しているように見える。
モータードライバ側もエラーは発生していない。
試しにタイムアウト時間を２秒から３０秒に変更して１日そのまま放置してみたが
問題が発生しなくなったので多分処理時間の問題と推測される。
とりあえずこれで様子を見てまた考える。

class Trinamic_control6110():
...            
    def __init__(self):
        # Changing the timeout due to slow process.
        # self.timeout = 2.
        self.timeout = 30.

reconnect()は多分これで入れていたのではないかと思うが、
呼ぶ必要はないのでこのまま消した状態とする。

**Comment by MiyoKouseki** [comment]
Complete the issue?
Could you move this issue to the Review/QA ?

**Comment by MiyoKouseki** [comment]
After his bug fix, this bugs have not happen according to his test.

Close.
